# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pa_ptr_pyqtnBteHz.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from mplwidget import MplWidget
from mplwidget2 import MplWidget2
from mplwidget3 import MplWidget3
from mplwidget4 import MplWidget4


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1194, 725)
        self.actionAjuda = QAction(MainWindow)
        self.actionAjuda.setObjectName(u"actionAjuda")
        self.actionSobre = QAction(MainWindow)
        self.actionSobre.setObjectName(u"actionSobre")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1191, 671))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 47, 16))
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 290, 47, 13))
        self.frame = QFrame(self.tab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 30, 421, 251))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Plain)
        self.frame.setLineWidth(25)
        self.frame.setMidLineWidth(8)
        self.layoutWidget = QWidget(self.frame)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(110, 190, 195, 31))
        self.gridLayout_3 = QGridLayout(self.layoutWidget)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.btCarregar_3 = QPushButton(self.layoutWidget)
        self.btCarregar_3.setObjectName(u"btCarregar_3")
        icon = QIcon()
        icon.addFile(u"resources/up_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btCarregar_3.setIcon(icon)

        self.gridLayout_3.addWidget(self.btCarregar_3, 0, 0, 1, 1)

        self.btLimpar_3 = QPushButton(self.layoutWidget)
        self.btLimpar_3.setObjectName(u"btLimpar_3")
        icon1 = QIcon()
        icon1.addFile(u"resources/lixeira.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btLimpar_3.setIcon(icon1)

        self.gridLayout_3.addWidget(self.btLimpar_3, 0, 1, 1, 1)

        self.layoutWidget1 = QWidget(self.frame)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(12, 10, 401, 165))
        self.gridLayout_10 = QGridLayout(self.layoutWidget1)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.label_28 = QLabel(self.layoutWidget1)
        self.label_28.setObjectName(u"label_28")

        self.gridLayout_10.addWidget(self.label_28, 0, 0, 1, 1)

        self.label_24 = QLabel(self.layoutWidget1)
        self.label_24.setObjectName(u"label_24")
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)

        self.gridLayout_10.addWidget(self.label_24, 1, 0, 1, 1)

        self.label_23 = QLabel(self.layoutWidget1)
        self.label_23.setObjectName(u"label_23")

        self.gridLayout_10.addWidget(self.label_23, 2, 0, 1, 1)

        self.label_29 = QLabel(self.layoutWidget1)
        self.label_29.setObjectName(u"label_29")

        self.gridLayout_10.addWidget(self.label_29, 3, 0, 1, 1)

        self.label_26 = QLabel(self.layoutWidget1)
        self.label_26.setObjectName(u"label_26")

        self.gridLayout_10.addWidget(self.label_26, 4, 0, 1, 1)

        self.btArquivoSaida_3 = QPushButton(self.layoutWidget1)
        self.btArquivoSaida_3.setObjectName(u"btArquivoSaida_3")
        icon2 = QIcon()
        icon2.addFile(u"resources/img_folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btArquivoSaida_3.setIcon(icon2)

        self.gridLayout_10.addWidget(self.btArquivoSaida_3, 4, 3, 1, 1)

        self.btArquivoBruto_3 = QPushButton(self.layoutWidget1)
        self.btArquivoBruto_3.setObjectName(u"btArquivoBruto_3")
        self.btArquivoBruto_3.setIcon(icon2)

        self.gridLayout_10.addWidget(self.btArquivoBruto_3, 0, 3, 1, 1)

        self.txParametros_3 = QLineEdit(self.layoutWidget1)
        self.txParametros_3.setObjectName(u"txParametros_3")

        self.gridLayout_10.addWidget(self.txParametros_3, 1, 1, 1, 1)

        self.cbGrupoAnimais_3 = QComboBox(self.layoutWidget1)
        self.cbGrupoAnimais_3.setObjectName(u"cbGrupoAnimais_3")

        self.gridLayout_10.addWidget(self.cbGrupoAnimais_3, 2, 1, 1, 1)

        self.txAnimal_3 = QLineEdit(self.layoutWidget1)
        self.txAnimal_3.setObjectName(u"txAnimal_3")

        self.gridLayout_10.addWidget(self.txAnimal_3, 3, 1, 1, 1)

        self.txArquivoSaida_3 = QLineEdit(self.layoutWidget1)
        self.txArquivoSaida_3.setObjectName(u"txArquivoSaida_3")

        self.gridLayout_10.addWidget(self.txArquivoSaida_3, 4, 1, 1, 1)

        self.txArquivoBruto_3 = QLineEdit(self.layoutWidget1)
        self.txArquivoBruto_3.setObjectName(u"txArquivoBruto_3")

        self.gridLayout_10.addWidget(self.txArquivoBruto_3, 0, 1, 1, 1)

        self.btParametros_3 = QPushButton(self.layoutWidget1)
        self.btParametros_3.setObjectName(u"btParametros_3")
        self.btParametros_3.setIcon(icon2)

        self.gridLayout_10.addWidget(self.btParametros_3, 1, 3, 1, 1)

        self.frame_2 = QFrame(self.tab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 310, 421, 321))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.rb15IQR_3 = QRadioButton(self.frame_2)
        self.buttonGroup = QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.rb15IQR_3)
        self.rb15IQR_3.setObjectName(u"rb15IQR_3")
        self.rb15IQR_3.setGeometry(QRect(65, 69, 81, 17))
        self.rb15IQR_3.setChecked(True)
        self.rb3IQR_3 = QRadioButton(self.frame_2)
        self.buttonGroup.addButton(self.rb3IQR_3)
        self.rb3IQR_3.setObjectName(u"rb3IQR_3")
        self.rb3IQR_3.setGeometry(QRect(65, 92, 81, 17))
        self.cbEtapas_3 = QComboBox(self.frame_2)
        self.cbEtapas_3.setObjectName(u"cbEtapas_3")
        self.cbEtapas_3.setGeometry(QRect(100, 15, 221, 20))
        self.label_30 = QLabel(self.frame_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(11, 15, 33, 16))
        self.label_31 = QLabel(self.frame_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 50, 221, 16))
        self.label_31.setFont(font)
        self.label_32 = QLabel(self.frame_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 148, 151, 16))
        self.label_32.setFont(font)
        self.rbNenhum_3 = QRadioButton(self.frame_2)
        self.buttonGroup.addButton(self.rbNenhum_3)
        self.rbNenhum_3.setObjectName(u"rbNenhum_3")
        self.rbNenhum_3.setGeometry(QRect(65, 115, 81, 17))
        self.rbRice_3 = QRadioButton(self.frame_2)
        self.buttonGroup_2 = QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(u"buttonGroup_2")
        self.buttonGroup_2.addButton(self.rbRice_3)
        self.rbRice_3.setObjectName(u"rbRice_3")
        self.rbRice_3.setGeometry(QRect(65, 168, 111, 17))
        self.rbRice_3.setChecked(True)
        self.rbEtapa_3 = QRadioButton(self.frame_2)
        self.buttonGroup_2.addButton(self.rbEtapa_3)
        self.rbEtapa_3.setObjectName(u"rbEtapa_3")
        self.rbEtapa_3.setGeometry(QRect(65, 218, 121, 17))
        self.horizontalSlider = QSlider(self.frame_2)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(80, 188, 121, 22))
        self.horizontalSlider.setMinimum(10)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setValue(100)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.spinBox = QSpinBox(self.frame_2)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(231, 188, 61, 22))
        self.spinBox.setMinimum(10)
        self.spinBox.setMaximum(100)
        self.spinBox.setValue(100)
        self.checkBoxTempo = QCheckBox(self.frame_2)
        self.checkBoxTempo.setObjectName(u"checkBoxTempo")
        self.checkBoxTempo.setGeometry(QRect(120, 246, 131, 17))
        self.layoutWidget2 = QWidget(self.frame_2)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(20, 281, 362, 31))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btAtualizar_3 = QPushButton(self.layoutWidget2)
        self.btAtualizar_3.setObjectName(u"btAtualizar_3")
        icon3 = QIcon()
        icon3.addFile(u"resources/atualizar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btAtualizar_3.setIcon(icon3)

        self.horizontalLayout_4.addWidget(self.btAtualizar_3)

        self.btInicioPa_3 = QPushButton(self.layoutWidget2)
        self.btInicioPa_3.setObjectName(u"btInicioPa_3")
        self.btInicioPa_3.setFont(font)
        icon4 = QIcon()
        icon4.addFile(u"resources/clock.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btInicioPa_3.setIcon(icon4)

        self.horizontalLayout_4.addWidget(self.btInicioPa_3)

        self.btSalvar_3 = QPushButton(self.layoutWidget2)
        self.btSalvar_3.setObjectName(u"btSalvar_3")
        icon5 = QIcon()
        icon5.addFile(u"resources/floppy-disk.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btSalvar_3.setIcon(icon5)

        self.horizontalLayout_4.addWidget(self.btSalvar_3)

        self.label_33 = QLabel(self.tab)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(440, 10, 47, 13))
        self.frame_3 = QFrame(self.tab)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(440, 30, 741, 601))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.MplWidget_3 = MplWidget(self.frame_3)
        self.MplWidget_3.setObjectName(u"MplWidget_3")
        self.MplWidget_3.setGeometry(QRect(10, 10, 721, 581))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_34 = QLabel(self.tab_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 150, 47, 13))
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 91, 16))
        self.frame_4 = QFrame(self.tab_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 30, 721, 111))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Plain)
        self.frame_4.setLineWidth(25)
        self.frame_4.setMidLineWidth(8)
        self.layoutWidget3 = QWidget(self.frame_4)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(7, 7, 595, 98))
        self.gridLayout = QGridLayout(self.layoutWidget3)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_40 = QLabel(self.layoutWidget3)
        self.label_40.setObjectName(u"label_40")

        self.gridLayout.addWidget(self.label_40, 0, 0, 1, 1)

        self.txArquivoBruto_4 = QLineEdit(self.layoutWidget3)
        self.txArquivoBruto_4.setObjectName(u"txArquivoBruto_4")

        self.gridLayout.addWidget(self.txArquivoBruto_4, 0, 1, 1, 1)

        self.btArquivoBruto_4 = QPushButton(self.layoutWidget3)
        self.btArquivoBruto_4.setObjectName(u"btArquivoBruto_4")
        self.btArquivoBruto_4.setIcon(icon2)

        self.gridLayout.addWidget(self.btArquivoBruto_4, 0, 2, 1, 1)

        self.label_35 = QLabel(self.layoutWidget3)
        self.label_35.setObjectName(u"label_35")

        self.gridLayout.addWidget(self.label_35, 0, 3, 1, 1)

        self.label_38 = QLabel(self.layoutWidget3)
        self.label_38.setObjectName(u"label_38")

        self.gridLayout.addWidget(self.label_38, 1, 0, 1, 1)

        self.txArquivoSaida_4 = QLineEdit(self.layoutWidget3)
        self.txArquivoSaida_4.setObjectName(u"txArquivoSaida_4")

        self.gridLayout.addWidget(self.txArquivoSaida_4, 1, 1, 1, 1)

        self.btArquivoSaida_4 = QPushButton(self.layoutWidget3)
        self.btArquivoSaida_4.setObjectName(u"btArquivoSaida_4")
        self.btArquivoSaida_4.setIcon(icon2)

        self.gridLayout.addWidget(self.btArquivoSaida_4, 1, 2, 1, 1)

        self.label_41 = QLabel(self.layoutWidget3)
        self.label_41.setObjectName(u"label_41")

        self.gridLayout.addWidget(self.label_41, 2, 0, 1, 1)

        self.txAnimal_4 = QLineEdit(self.layoutWidget3)
        self.txAnimal_4.setObjectName(u"txAnimal_4")

        self.gridLayout.addWidget(self.txAnimal_4, 2, 1, 1, 1)

        self.label_4 = QLabel(self.layoutWidget3)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 1)

        self.label_5 = QLabel(self.layoutWidget3)
        self.label_5.setObjectName(u"label_5")
        font1 = QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.label_5.setFont(font1)

        self.gridLayout.addWidget(self.label_5, 2, 4, 1, 1)

        self.cbGrupoAnimais_4 = QComboBox(self.layoutWidget3)
        self.cbGrupoAnimais_4.setObjectName(u"cbGrupoAnimais_4")

        self.gridLayout.addWidget(self.cbGrupoAnimais_4, 0, 4, 1, 1)

        self.layoutWidget4 = QWidget(self.frame_4)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(620, 20, 95, 67))
        self.gridLayout_2 = QGridLayout(self.layoutWidget4)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.btCarregar_4 = QPushButton(self.layoutWidget4)
        self.btCarregar_4.setObjectName(u"btCarregar_4")
        self.btCarregar_4.setIcon(icon)

        self.gridLayout_2.addWidget(self.btCarregar_4, 0, 0, 1, 1)

        self.btLimpar_4 = QPushButton(self.layoutWidget4)
        self.btLimpar_4.setObjectName(u"btLimpar_4")
        self.btLimpar_4.setIcon(icon1)

        self.gridLayout_2.addWidget(self.btLimpar_4, 1, 0, 1, 1)

        self.frame_6 = QFrame(self.tab_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 170, 1161, 461))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Plain)
        self.MplWidget2 = MplWidget2(self.frame_6)
        self.MplWidget2.setObjectName(u"MplWidget2")
        self.MplWidget2.setGeometry(QRect(10, 10, 1141, 441))
        self.frame_5 = QFrame(self.tab_2)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(740, 30, 431, 111))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Plain)
        self.label_42 = QLabel(self.frame_5)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 40, 33, 16))
        self.cbEtapas_4 = QComboBox(self.frame_5)
        self.cbEtapas_4.setObjectName(u"cbEtapas_4")
        self.cbEtapas_4.setGeometry(QRect(60, 40, 241, 20))
        self.layoutWidget5 = QWidget(self.frame_5)
        self.layoutWidget5.setObjectName(u"layoutWidget5")
        self.layoutWidget5.setGeometry(QRect(320, 20, 95, 67))
        self.gridLayout_4 = QGridLayout(self.layoutWidget5)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btAtualizar_4 = QPushButton(self.layoutWidget5)
        self.btAtualizar_4.setObjectName(u"btAtualizar_4")
        self.btAtualizar_4.setIcon(icon3)

        self.gridLayout_4.addWidget(self.btAtualizar_4, 0, 0, 1, 1)

        self.btSalvar_4 = QPushButton(self.layoutWidget5)
        self.btSalvar_4.setObjectName(u"btSalvar_4")
        self.btSalvar_4.setIcon(icon5)

        self.gridLayout_4.addWidget(self.btSalvar_4, 1, 0, 1, 1)

        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(740, 10, 91, 16))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_6 = QLabel(self.tab_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(11, 10, 50, 13))
        self.label_10 = QLabel(self.tab_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(12, 290, 47, 13))
        self.frame_9 = QFrame(self.tab_3)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(440, 30, 741, 601))
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Plain)
        self.MplWidget3 = MplWidget3(self.frame_9)
        self.MplWidget3.setObjectName(u"MplWidget3")
        self.MplWidget3.setGeometry(QRect(10, 10, 721, 581))
        self.label_46 = QLabel(self.tab_3)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(440, 10, 47, 13))
        self.frame_7 = QFrame(self.tab_3)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 30, 421, 251))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Plain)
        self.frame_7.setLineWidth(25)
        self.frame_7.setMidLineWidth(8)
        self.layoutWidget_3 = QWidget(self.frame_7)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(110, 190, 195, 31))
        self.gridLayout_5 = QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.btCarregar_5 = QPushButton(self.layoutWidget_3)
        self.btCarregar_5.setObjectName(u"btCarregar_5")
        self.btCarregar_5.setIcon(icon)

        self.gridLayout_5.addWidget(self.btCarregar_5, 0, 0, 1, 1)

        self.btLimpar_5 = QPushButton(self.layoutWidget_3)
        self.btLimpar_5.setObjectName(u"btLimpar_5")
        self.btLimpar_5.setIcon(icon1)

        self.gridLayout_5.addWidget(self.btLimpar_5, 0, 1, 1, 1)

        self.layoutWidget_4 = QWidget(self.frame_7)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(10, 10, 401, 165))
        self.gridLayout_11 = QGridLayout(self.layoutWidget_4)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.label_25 = QLabel(self.layoutWidget_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setFont(font)

        self.gridLayout_11.addWidget(self.label_25, 1, 0, 1, 1)

        self.btParametros_4 = QPushButton(self.layoutWidget_4)
        self.btParametros_4.setObjectName(u"btParametros_4")
        self.btParametros_4.setIcon(icon2)

        self.gridLayout_11.addWidget(self.btParametros_4, 1, 3, 1, 1)

        self.label_36 = QLabel(self.layoutWidget_4)
        self.label_36.setObjectName(u"label_36")

        self.gridLayout_11.addWidget(self.label_36, 0, 0, 1, 1)

        self.cbGrupoAnimais_5 = QComboBox(self.layoutWidget_4)
        self.cbGrupoAnimais_5.setObjectName(u"cbGrupoAnimais_5")

        self.gridLayout_11.addWidget(self.cbGrupoAnimais_5, 2, 1, 1, 1)

        self.txAnimal_5 = QLineEdit(self.layoutWidget_4)
        self.txAnimal_5.setObjectName(u"txAnimal_5")

        self.gridLayout_11.addWidget(self.txAnimal_5, 3, 1, 1, 1)

        self.label_27 = QLabel(self.layoutWidget_4)
        self.label_27.setObjectName(u"label_27")

        self.gridLayout_11.addWidget(self.label_27, 2, 0, 1, 1)

        self.txArquivoBruto_5 = QLineEdit(self.layoutWidget_4)
        self.txArquivoBruto_5.setObjectName(u"txArquivoBruto_5")

        self.gridLayout_11.addWidget(self.txArquivoBruto_5, 0, 1, 1, 1)

        self.btArquivoBruto_5 = QPushButton(self.layoutWidget_4)
        self.btArquivoBruto_5.setObjectName(u"btArquivoBruto_5")
        self.btArquivoBruto_5.setIcon(icon2)

        self.gridLayout_11.addWidget(self.btArquivoBruto_5, 0, 3, 1, 1)

        self.label_37 = QLabel(self.layoutWidget_4)
        self.label_37.setObjectName(u"label_37")

        self.gridLayout_11.addWidget(self.label_37, 3, 0, 1, 1)

        self.txParametros_4 = QLineEdit(self.layoutWidget_4)
        self.txParametros_4.setObjectName(u"txParametros_4")

        self.gridLayout_11.addWidget(self.txParametros_4, 1, 1, 1, 1)

        self.frame_8 = QFrame(self.tab_3)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(10, 310, 421, 321))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Plain)
        self.rb15IQR_4 = QRadioButton(self.frame_8)
        self.buttonGroup_3 = QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName(u"buttonGroup_3")
        self.buttonGroup_3.addButton(self.rb15IQR_4)
        self.rb15IQR_4.setObjectName(u"rb15IQR_4")
        self.rb15IQR_4.setGeometry(QRect(65, 69, 91, 17))
        self.rb15IQR_4.setChecked(True)
        self.rb3IQR_4 = QRadioButton(self.frame_8)
        self.buttonGroup_3.addButton(self.rb3IQR_4)
        self.rb3IQR_4.setObjectName(u"rb3IQR_4")
        self.rb3IQR_4.setGeometry(QRect(65, 92, 81, 17))
        self.cbEtapas_5 = QComboBox(self.frame_8)
        self.cbEtapas_5.setObjectName(u"cbEtapas_5")
        self.cbEtapas_5.setGeometry(QRect(100, 15, 221, 20))
        self.label_43 = QLabel(self.frame_8)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(11, 15, 33, 16))
        self.label_44 = QLabel(self.frame_8)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 50, 221, 16))
        self.label_44.setFont(font)
        self.label_45 = QLabel(self.frame_8)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 148, 151, 16))
        self.label_45.setFont(font)
        self.rbNenhum_4 = QRadioButton(self.frame_8)
        self.buttonGroup_3.addButton(self.rbNenhum_4)
        self.rbNenhum_4.setObjectName(u"rbNenhum_4")
        self.rbNenhum_4.setGeometry(QRect(65, 115, 81, 17))
        self.rbRice_4 = QRadioButton(self.frame_8)
        self.buttonGroup_4 = QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName(u"buttonGroup_4")
        self.buttonGroup_4.addButton(self.rbRice_4)
        self.rbRice_4.setObjectName(u"rbRice_4")
        self.rbRice_4.setGeometry(QRect(65, 168, 111, 17))
        self.rbRice_4.setChecked(True)
        self.rbEtapa_4 = QRadioButton(self.frame_8)
        self.buttonGroup_4.addButton(self.rbEtapa_4)
        self.rbEtapa_4.setObjectName(u"rbEtapa_4")
        self.rbEtapa_4.setGeometry(QRect(65, 218, 121, 17))
        self.horizontalSlider_2 = QSlider(self.frame_8)
        self.horizontalSlider_2.setObjectName(u"horizontalSlider_2")
        self.horizontalSlider_2.setGeometry(QRect(80, 188, 121, 22))
        self.horizontalSlider_2.setMinimum(10)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setValue(100)
        self.horizontalSlider_2.setOrientation(Qt.Horizontal)
        self.spinBox_2 = QSpinBox(self.frame_8)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(231, 188, 61, 22))
        self.spinBox_2.setMinimum(10)
        self.spinBox_2.setMaximum(100)
        self.spinBox_2.setValue(100)
        self.widget = QWidget(self.frame_8)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(80, 260, 228, 31))
        self.gridLayout_8 = QGridLayout(self.widget)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.btAtualizar_5 = QPushButton(self.widget)
        self.btAtualizar_5.setObjectName(u"btAtualizar_5")
        icon6 = QIcon()
        icon6.addFile(u"resources/plus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btAtualizar_5.setIcon(icon6)

        self.gridLayout_8.addWidget(self.btAtualizar_5, 0, 0, 1, 1)

        self.btLimpar_7 = QPushButton(self.widget)
        self.btLimpar_7.setObjectName(u"btLimpar_7")
        self.btLimpar_7.setIcon(icon1)

        self.gridLayout_8.addWidget(self.btLimpar_7, 0, 1, 1, 1)

        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.frame_10 = QFrame(self.tab_4)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(10, 170, 1161, 461))
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Plain)
        self.MplWidget4 = MplWidget4(self.frame_10)
        self.MplWidget4.setObjectName(u"MplWidget4")
        self.MplWidget4.setGeometry(QRect(10, 10, 1161, 441))
        self.label_11 = QLabel(self.tab_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 10, 91, 16))
        self.label_52 = QLabel(self.tab_4)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(10, 150, 47, 13))
        self.frame_11 = QFrame(self.tab_4)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(10, 30, 721, 111))
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Plain)
        self.frame_11.setLineWidth(25)
        self.frame_11.setMidLineWidth(8)
        self.layoutWidget_2 = QWidget(self.frame_11)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(7, 7, 595, 98))
        self.gridLayout_6 = QGridLayout(self.layoutWidget_2)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.txArquivoBruto_6 = QLineEdit(self.layoutWidget_2)
        self.txArquivoBruto_6.setObjectName(u"txArquivoBruto_6")

        self.gridLayout_6.addWidget(self.txArquivoBruto_6, 0, 1, 1, 1)

        self.label_8 = QLabel(self.layoutWidget_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setFont(font1)

        self.gridLayout_6.addWidget(self.label_8, 1, 4, 1, 1)

        self.label_51 = QLabel(self.layoutWidget_2)
        self.label_51.setObjectName(u"label_51")

        self.gridLayout_6.addWidget(self.label_51, 1, 0, 1, 1)

        self.label_47 = QLabel(self.layoutWidget_2)
        self.label_47.setObjectName(u"label_47")

        self.gridLayout_6.addWidget(self.label_47, 0, 0, 1, 1)

        self.btArquivoBruto_6 = QPushButton(self.layoutWidget_2)
        self.btArquivoBruto_6.setObjectName(u"btArquivoBruto_6")
        self.btArquivoBruto_6.setIcon(icon2)

        self.gridLayout_6.addWidget(self.btArquivoBruto_6, 0, 2, 1, 1)

        self.label_7 = QLabel(self.layoutWidget_2)
        self.label_7.setObjectName(u"label_7")

        self.gridLayout_6.addWidget(self.label_7, 1, 3, 1, 1)

        self.cbGrupoAnimais_6 = QComboBox(self.layoutWidget_2)
        self.cbGrupoAnimais_6.setObjectName(u"cbGrupoAnimais_6")

        self.gridLayout_6.addWidget(self.cbGrupoAnimais_6, 0, 4, 1, 1)

        self.txAnimal_6 = QLineEdit(self.layoutWidget_2)
        self.txAnimal_6.setObjectName(u"txAnimal_6")

        self.gridLayout_6.addWidget(self.txAnimal_6, 1, 1, 1, 1)

        self.label_48 = QLabel(self.layoutWidget_2)
        self.label_48.setObjectName(u"label_48")

        self.gridLayout_6.addWidget(self.label_48, 0, 3, 1, 1)

        self.layoutWidget_5 = QWidget(self.frame_11)
        self.layoutWidget_5.setObjectName(u"layoutWidget_5")
        self.layoutWidget_5.setGeometry(QRect(620, 20, 95, 67))
        self.gridLayout_7 = QGridLayout(self.layoutWidget_5)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.btCarregar_6 = QPushButton(self.layoutWidget_5)
        self.btCarregar_6.setObjectName(u"btCarregar_6")
        self.btCarregar_6.setIcon(icon)

        self.gridLayout_7.addWidget(self.btCarregar_6, 0, 0, 1, 1)

        self.btLimpar_6 = QPushButton(self.layoutWidget_5)
        self.btLimpar_6.setObjectName(u"btLimpar_6")
        self.btLimpar_6.setIcon(icon1)

        self.gridLayout_7.addWidget(self.btLimpar_6, 1, 0, 1, 1)

        self.label_13 = QLabel(self.tab_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(740, 10, 91, 16))
        self.frame_12 = QFrame(self.tab_4)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(740, 30, 431, 111))
        self.frame_12.setFrameShape(QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Plain)
        self.label_54 = QLabel(self.frame_12)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(10, 40, 33, 16))
        self.cbEtapas_7 = QComboBox(self.frame_12)
        self.cbEtapas_7.setObjectName(u"cbEtapas_7")
        self.cbEtapas_7.setGeometry(QRect(60, 40, 191, 20))
        self.widget1 = QWidget(self.frame_12)
        self.widget1.setObjectName(u"widget1")
        self.widget1.setGeometry(QRect(290, 20, 131, 67))
        self.formLayout = QFormLayout(self.widget1)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.btAtualizar_7 = QPushButton(self.widget1)
        self.btAtualizar_7.setObjectName(u"btAtualizar_7")
        self.btAtualizar_7.setIcon(icon6)

        self.formLayout.setWidget(0, QFormLayout.SpanningRole, self.btAtualizar_7)

        self.btLimpar_8 = QPushButton(self.widget1)
        self.btLimpar_8.setObjectName(u"btLimpar_8")
        self.btLimpar_8.setIcon(icon1)

        self.formLayout.setWidget(1, QFormLayout.SpanningRole, self.btLimpar_8)

        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1194, 26))
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menuMenu.addAction(self.actionAjuda)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionSobre)

        self.retranslateUi(MainWindow)
        self.spinBox.valueChanged.connect(self.horizontalSlider.setValue)
        self.horizontalSlider.valueChanged.connect(self.spinBox.setValue)
        self.horizontalSlider_2.sliderMoved.connect(self.spinBox_2.setValue)
        self.spinBox_2.valueChanged.connect(self.horizontalSlider_2.setValue)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"An\u00e1lise PA & Ptr", None))
        self.actionAjuda.setText(QCoreApplication.translate("MainWindow", u"Ajuda", None))
        self.actionSobre.setText(QCoreApplication.translate("MainWindow", u"Sobre", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Setup", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Controle", None))
        self.btCarregar_3.setText(QCoreApplication.translate("MainWindow", u" Carregar", None))
        self.btLimpar_3.setText(QCoreApplication.translate("MainWindow", u" Limpar", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"1. Arquivo Dados Brutos", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"2. Arquivo Par\u00e2metros (PA)", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"3. Grupo de Animais", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"4. Animal #", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"5. Arquivo Sa\u00edda", None))
        self.btArquivoSaida_3.setText("")
        self.btArquivoBruto_3.setText("")
        self.cbGrupoAnimais_3.setCurrentText("")
        self.btParametros_3.setText("")
        self.rb15IQR_3.setText(QCoreApplication.translate("MainWindow", u"1.5 * IQR", None))
        self.rb3IQR_3.setText(QCoreApplication.translate("MainWindow", u"3 * IQR", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Etapas", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"M\u00e9todo Detec\u00e7\u00e3o Outliers PA (Tukey)", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Janela C\u00e1lculo Tukey (PA)", None))
        self.rbNenhum_3.setText(QCoreApplication.translate("MainWindow", u"Nenhum", None))
        self.rbRice_3.setText(QCoreApplication.translate("MainWindow", u"Regra de Rice", None))
        self.rbEtapa_3.setText(QCoreApplication.translate("MainWindow", u"Etapa Completa", None))
        self.checkBoxTempo.setText(QCoreApplication.translate("MainWindow", u"Ajuste de Tempo", None))
        self.btAtualizar_3.setText(QCoreApplication.translate("MainWindow", u" Atualizar", None))
        self.btInicioPa_3.setText(QCoreApplication.translate("MainWindow", u" Selecionar In\u00edcio (PA)", None))
        self.btSalvar_3.setText(QCoreApplication.translate("MainWindow", u" Salvar", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Gr\u00e1ficos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"An\u00e1lise PA", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Gr\u00e1ficos", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Setup", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"1. Arquivo Dados Brutos", None))
        self.btArquivoBruto_4.setText("")
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"4. Grupo de Animais", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"2. Arquivo Sa\u00edda", None))
        self.btArquivoSaida_4.setText("")
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"3. Animal #", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Arquivo Vers\u00e3o", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.cbGrupoAnimais_4.setCurrentText("")
        self.btCarregar_4.setText(QCoreApplication.translate("MainWindow", u" Carregar", None))
        self.btLimpar_4.setText(QCoreApplication.translate("MainWindow", u" Limpar", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Etapas", None))
        self.btAtualizar_4.setText(QCoreApplication.translate("MainWindow", u" Atualizar", None))
        self.btSalvar_4.setText(QCoreApplication.translate("MainWindow", u" Salvar", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Controle", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"An\u00e1lise Ptr", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Setup", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Controle", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Gr\u00e1ficos", None))
        self.btCarregar_5.setText(QCoreApplication.translate("MainWindow", u" Carregar", None))
        self.btLimpar_5.setText(QCoreApplication.translate("MainWindow", u" Limpar", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"2. Arquivo Par\u00e2metros (PA)", None))
        self.btParametros_4.setText("")
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"1. Arquivo Dados Brutos", None))
        self.cbGrupoAnimais_5.setCurrentText("")
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"3. Grupo de Animais", None))
        self.btArquivoBruto_5.setText("")
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"4. Animal #", None))
        self.rb15IQR_4.setText(QCoreApplication.translate("MainWindow", u"1.5 * IQR", None))
        self.rb3IQR_4.setText(QCoreApplication.translate("MainWindow", u"3 * IQR", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Etapas", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"M\u00e9todo Detec\u00e7\u00e3o Outliers PA (Tukey)", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Janela C\u00e1lculo Tukey (PA)", None))
        self.rbNenhum_4.setText(QCoreApplication.translate("MainWindow", u"Nenhum", None))
        self.rbRice_4.setText(QCoreApplication.translate("MainWindow", u"Regra de Rice", None))
        self.rbEtapa_4.setText(QCoreApplication.translate("MainWindow", u"Etapa Completa", None))
        self.btAtualizar_5.setText(QCoreApplication.translate("MainWindow", u" Incluir", None))
        self.btLimpar_7.setText(QCoreApplication.translate("MainWindow", u" Limpar Gr\u00e1ficos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"An\u00e1lise Comparativa PA", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Setup", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Gr\u00e1ficos", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"3. Animal #", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"1. Arquivo Dados Brutos", None))
        self.btArquivoBruto_6.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Arquivo Vers\u00e3o", None))
        self.cbGrupoAnimais_6.setCurrentText("")
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"4. Grupo de Animais", None))
        self.btCarregar_6.setText(QCoreApplication.translate("MainWindow", u" Carregar", None))
        self.btLimpar_6.setText(QCoreApplication.translate("MainWindow", u" Limpar", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Controle", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"Etapas", None))
        self.btAtualizar_7.setText(QCoreApplication.translate("MainWindow", u"Incluir", None))
        self.btLimpar_8.setText(QCoreApplication.translate("MainWindow", u" Limpar Gr\u00e1ficos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"An\u00e1lise Comparativa Ptr", None))
        self.menuMenu.setTitle(QCoreApplication.translate("MainWindow", u"Menu", None))
    # retranslateUi

